name: Armin's blog
description: Random posts mainly for me to remember things
meta_description: "Armin's random ramblings"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog.armin.io'
author:         'Armin Krauss'
